name: fireverse
description: Multi platform firebase plugin.
version: 0.0.12
homepage: https://github.com/codekaze/fireverse

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.1
  grpc: ^3.0.0
  protobuf: ^2.0.0
  fixnum: ^1.0.0

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.10.0
