name: monalisa
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  mysql1: ^0.20.0
  shelf: ^1.4.0
  shelf_multipart: ^1.0.0
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1
  uuid: ^3.0.6
