name: container_server_example
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1 
  fireverse:
    path:
      ./fireverse
  mysql1: ^0.20.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.1
  test: ^1.15.0
  test_process: ^2.0.0
